### ISSUE TITLE
mongo-cxx-driver cannot build

### ISSUE THREAD

**Issue by byzhang** [Tokutek/mongo#184]
Here are the errors: (it seems just need to update SConstruct to have the toku related settings?)

src/mongo/db/commands.h: In member function 'virtual int mongo::FileopsCommand::txnFlags() const':
src/mongo/db/commands.h:181:47: error: 'DB_SERIALIZABLE' was not declared in this scope
src/mongo/db/commands.h: In member function 'virtual int mongo::ModifyCommand::txnFlags() const':
src/mongo/db/commands.h:197:47: error: 'DB_SERIALIZABLE' was not declared in this scope
src/mongo/db/commands.h: In member function 'virtual int mongo::QueryCommand::txnFlags() const':
src/mongo/db/commands.h:210:65: error: 'DB_TXN_READ_ONLY' was not declared in this scope

This results from trying to build what's in mongo-cxx-driver.tgz.  We probably need to include db.h in that tarball so that it can build on its own.
